Add readthedocsfile
simai-ml/MAPIE pull request #16
Opened 2021-04-16 16:45 UTC by vtaquet

2021-04-16 18:41 UTC, gmartinonQM commented on .readthedocs.yml
> +  environment: environment_dev.yml
Pour être plus rapide, il faudrait un environnement minimal (sans mypy, flake8, pytest etc.)
De plus, il faudrait un environnement avec python 3.8 et pas 3.9 (d'ailleurs, est-on obligé de préciser la version de python puisqu'elle est déjà précisée dans le yml ?

2021-04-17 18:46 UTC, vtaquet commented on .readthedocs.yml
> +  environment: environment_dev.yml
J'ai créé un fichier `environment_doc` en supprimant les packages non-nécessaire et en modifiant la version de python à 3.8.

2021-04-18 19:52 UTC, gmartinonQM requested changes
Histoire de ne pas encombrer le répertoire racine, je propose de placer l'environnement de génération de la doc dans le répertoire doc/

2021-04-18 19:52 UTC, gmartinonQM commented on environment_doc.yml
> +name: mapie
`mapie-doc`

2021-04-18 19:52 UTC, gmartinonQM commented on .readthedocs.yml
> +  environment: environment_doc.yml
`environment: doc/environment.yml`

2021-04-19 07:37 UTC, vtaquet commented on environment_doc.yml
> +name: mapie
Modifié.

2021-04-19 07:37 UTC, vtaquet commented on .readthedocs.yml
> +  environment: environment_doc.yml
Déplacé.

2021-04-19 07:44 UTC, merged