Update Makefile to copy quickstart image in images/ folder
simai-ml/MAPIE pull request #41
Opened 2021-05-07 14:40 UTC by vtaquet

# Description

Update doc Makefile to copy image generated by `plot_toy_model.py` in `doc/images/` folder.

## Type of change

Please check options that are relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

# Checklist:

- [x] I have read the [contributing guidelines](https://github.com/simai-ml/MAPIE/blob/master/CONTRIBUTING.rst)
- Not relevant. I have updated the [HISTORY.rst](https://github.com/simai-ml/MAPIE/blob/master/HISTORY.rst) and [AUTHORS.rst](https://github.com/simai-ml/MAPIE/blob/master/AUTHORS.rst) files
- Not relevant. Linting passes successfully : `flake8 . --exclude=doc`
- Not relevant. Typing passes successfully : `mypy mapie examples --strict --config-file mypy.ini`
- Not relevant. Unit tests pass successfully : `pytest -vs --doctest-modules mapie`
- Not relevant. Coverage is 100% : `pytest -vs --doctest-modules --cov-branch --cov=mapie --pyargs mapie`
- [x] Documentation builds successfully : `cd doc; make clean; make html`

2021-05-07 19:53 UTC, gmartinonQM requested changes

2021-05-07 19:53 UTC, gmartinonQM commented on doc/Makefile
> +copyquickstartimage:
Hum, ok mais mais cette commande n'est jamais appelée quand on fait `make html` ...

2021-05-10 10:14 UTC, vtaquet commented on doc/Makefile
> +copyquickstartimage:
Commande ajoutée.

2021-05-10 13:32 UTC, vtaquet commented on doc/Makefile
> +	cp _build/html/_images/sphx_glr_plot_toy_model_001.png images/quickstart_1.png
Oui, j'hésitais à la garder mais en pratique on ne l'utilisera pas de manière indépendante.

2021-05-10 13:49 UTC, merged